-- TABLA: PEOPLE (Integrantes Globales)
create table people (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA: GROUPS (Grupos de Gastos)
create table groups (
  id bigint generated by default as identity primary key,
  name text not null,
  status text default 'PENDING',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  paid_at timestamp with time zone
);

-- TABLA: GROUP_MEMBERS (Relación Muchos a Muchos: Grupos <-> Personas)
create table group_members (
  group_id bigint references groups(id) on delete cascade,
  person_id bigint references people(id) on delete cascade,
  primary key (group_id, person_id)
);

-- TABLA: EXPENSES (Gastos Individuales)
create table expenses (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  payer_id bigint references people(id) on delete set null,
  description text,
  amount numeric not null,
  type text check (type in ('SHARED', 'LOAN')),
  borrower_id bigint references people(id) on delete set null, -- Para prestamos
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA: EXPENSE_INVOLVED (Para gastos compartidos: Quienes se dividen el gasto)
create table expense_involved (
  expense_id bigint references expenses(id) on delete cascade,
  person_id bigint references people(id) on delete cascade,
  primary key (expense_id, person_id)
);

-- HABILITAR PUBLIC ACCESS (para que funcione con la Anon Key sin login por ahora)
-- NOTA: Esto permite que cualquiera con tu clave Anon lea/escriba. Ideal para prototipo.
alter table people enable row level security;
create policy "Public Access People" on people for all using (true) with check (true);

alter table groups enable row level security;
create policy "Public Access Groups" on groups for all using (true) with check (true);

alter table group_members enable row level security;
create policy "Public Access GroupMembers" on group_members for all using (true) with check (true);

alter table expenses enable row level security;
create policy "Public Access Expenses" on expenses for all using (true) with check (true);

alter table expense_involved enable row level security;
create policy "Public Access ExpenseInvolved" on expense_involved for all using (true) with check (true);
